export const networks = [
    {
      id: 1,
      chain_bytes: "eth",
      name: "Ethereum",
      slug: "ethereum",
      logo: "https://gfa.nyc3.digitaloceanspaces.com/testapp/testdir/ETH.png",
      symbol: "eth",
      displaySymbol: "ETH",
      currency: "ETH",
      rpc_url: `https://mainnet.infura.io/v3/${process.env.INFURA_API}`,
      explorer: "https://etherscan.io/",
      allowed: true,
    },
    {
      id: 56,
      chain_bytes: "bsc",
      name: "BSC Chain",
      slug: "binancecoin",
      logo: "https://gfa.nyc3.digitaloceanspaces.com/testapp/testdir/BNB.png",
      symbol: "bsc",
      displaySymbol: "BSC",
      currency: "BNB",
      rpc_url: "https://bsc-dataseed.binance.org/",
      explorer: "https://bscscan.com/",
      allowed: true,
    },
    {
      id: 137,
      chain_bytes: "poly",
      name: "Polygon",
      slug: "matic-network",
      logo: "https://gfa.nyc3.digitaloceanspaces.com/testapp/testdir/MATIC.png",
      symbol: "polygon",
      displaySymbol: "Polygon",
      curreny: "MATIC",
      rpc_url: "https://rpc-mainnet.maticvigil.com",
      explorer: "https://polygonscan.com/",
      allowed: true,
    },
  ];